version: '3.3'

services:
  app:
    build: .
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/mini_blog:cached
      - gems:/usr/local/lib/ruby/gems
      - local_bin:/usr/local/bin
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_USER=postgres
    tty: true
    command: [ "bash", "-c", "rm -f tmp/pids/server.pid; ./bin/rails server -b 0.0.0.0" ]

  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  gems:
  local_bin:
  postgres-data:
